In [1]:
#import python libraries
import pandas as pd
import numpy as np
import random
import string

In [2]:
df = pd.read_csv("EdStatsCountry.csv") #Using this code we can upload the data
df.head(5) #Displays the first 5 rows of df.

,Country_Code,Short_Name,Long_Name,2-alpha_code,Currency_Unit,Region,Income_Group,WB-2_code,National_accounts_base_year,National_accounts_reference_year,...,Government_Accounting_concept,IMF_data_dissemination_standard,Latest_population_census,Latest_household_survey,Source_of_most_recent_Income_and_expenditure_data,Vital_registration_complete,Latest_agricultural_census,Latest_industrial_ data,Latest_trade_data,Latest_water_withdrawal_data
0,ABW,Aruba,Aruba,AW,Aruban florin,Latin America & Caribbean,High income: nonOECD,AW,2000,1996,...,Consolidated central government,General Data Dissemination System (GDDS),2010,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",Yes,2013/14,2010,2012,2000
1,AFG,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,South Asia,Low income,AF,2002/03,1996,...,Consolidated central government,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",Yes,2013/14,2010,2012,2000
2,AGO,Angola,People's Republic of Angola,AO,Angolan kwanza,Sub-Saharan Africa,Upper middle income,AO,2002,1996,...,Budgetary central government,General Data Dissemination System (GDDS),1970,"Malaria Indicator Survey (MIS), 2011","Integrated household survey (IHS), 2008",Yes,2015,2010,2012,2005
3,ALB,Albania,Republic of Albania,AL,Albanian lek,Europe & Central Asia,Upper middle income,AL,Original chained constant price data are resca...,1996,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010,2012,2006
4,AND,Andorra,Principality of Andorra,AD,Euro,Europe & Central Asia,High income: nonOECD,AD,1990,1996,...,Consolidated central government,General Data Dissemination System (GDDS),2011. Population figures compiled from adminis...,"Multiple Indicator Cluster Survey (MICS), 2011/12","Integrated household survey (IHS), 2012",Yes,2012,2002,2006,2005

In [3]:
df.shape #Show the how many column & row idividual in the particular table

(239, 29)

In [4]:
df.columns #Returns the list of column names

Index(['Country_Code', 'Short_Name', 'Long_Name', '2-alpha_code',
       'Currency_Unit', 'Region', 'Income_Group', 'WB-2_code',
       'National_accounts_base_year', 'National_accounts_reference_year',
       'SNA_price_valuation', 'Lending_category', 'Other_groups',
       'System_of_National_Accounts', 'Alternative_conversion_factor',
       'PPP_survey_year', 'Balance_of_Payments_Manual_in_use',
       'External_debt_Reporting_status', 'System_of_trade',
       'Government_Accounting_concept', 'IMF_data_dissemination_standard',
       'Latest_population_census', 'Latest_household_survey',
       'Source_of_most_recent_Income_and_expenditure_data',
       'Vital_registration_complete', 'Latest_agricultural_census',
       'Latest_industrial_ data', 'Latest_trade_data',
       'Latest_water_withdrawal_data'],
      dtype='object')

In [5]:
df.info() #That will print information on all the columns.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239 entries, 0 to 238
Data columns (total 29 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Country_Code                                       239 non-null    object
 1   Short_Name                                         239 non-null    object
 2   Long_Name                                          239 non-null    object
 3   2-alpha_code                                       238 non-null    object
 4   Currency_Unit                                      239 non-null    object
 5   Region                                             239 non-null    object
 6   Income_Group                                       239 non-null    object
 7   WB-2_code                                          238 non-null    object
 8   National_accounts_base_year                        239 non-null    object
 9   National_accounts_reference_year                   239 non-null    int64
 10  SNA_price_valuation                                239 non-null    object
 11  Lending_category                                   239 non-null    object
 12  Other_groups                                       239 non-null    object
 13  System_of_National_Accounts                        239 non-null    object
 14  Alternative_conversion_factor                      239 non-null    object
 15  PPP_survey_year                                    239 non-null    object
 16  Balance_of_Payments_Manual_in_use                  239 non-null    object
 17  External_debt_Reporting_status                     239 non-null    object
 18  System_of_trade                                    239 non-null    object
 19  Government_Accounting_concept                      239 non-null    object
 20  IMF_data_dissemination_standard                    239 non-null    object
 21  Latest_population_census                           239 non-null    object
 22  Latest_household_survey                            239 non-null    object
 23  Source_of_most_recent_Income_and_expenditure_data  239 non-null    object
 24  Vital_registration_complete                        239 non-null    object
 25  Latest_agricultural_census                         239 non-null    object
 26  Latest_industrial_ data                            239 non-null    int64
 27  Latest_trade_data                                  239 non-null    int64
 28  Latest_water_withdrawal_data                       239 non-null    object
dtypes: int64(3), object(26)
memory usage: 54.3+ KB

In [6]:
df['Income_Group'].unique() #Show all type of "Income_Group" name

array(['High income: nonOECD', 'Low income', 'Upper middle income',
       'Lower middle income', 'High income: OECD'], dtype=object)

# Data Filtering

In [7]:
#Filters 'df' for rows where 'Income_Group' is 'Upper middle income'.
df_recet = df[df['Income_Group'] == 'Upper middle income']

# Preview the first few rows of 'df_recet'
df_recet.head()

,Country_Code,Short_Name,Long_Name,2-alpha_code,Currency_Unit,Region,Income_Group,WB-2_code,National_accounts_base_year,National_accounts_reference_year,...,Government_Accounting_concept,IMF_data_dissemination_standard,Latest_population_census,Latest_household_survey,Source_of_most_recent_Income_and_expenditure_data,Vital_registration_complete,Latest_agricultural_census,Latest_industrial_ data,Latest_trade_data,Latest_water_withdrawal_data
2,AGO,Angola,People's Republic of Angola,AO,Angolan kwanza,Sub-Saharan Africa,Upper middle income,AO,2002,1996,...,Budgetary central government,General Data Dissemination System (GDDS),1970,"Malaria Indicator Survey (MIS), 2011","Integrated household survey (IHS), 2008",Yes,2015,2010,2012,2005
3,ALB,Albania,Republic of Albania,AL,Albanian lek,Europe & Central Asia,Upper middle income,AL,Original chained constant price data are resca...,1996,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010,2012,2006
7,ARG,Argentina,Argentine Republic,AR,Argentine peso,Latin America & Caribbean,Upper middle income,AR,2004,1996,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2010,"Multiple Indicator Cluster Survey (MICS), 2011/12","Integrated household survey (IHS), 2012",Yes,2013,2002,2012,2000
9,ASM,American Samoa,American Samoa,AS,U.S. dollar,East Asia & Pacific,Upper middle income,AS,2006,2012,...,Budgetary central government,General Data Dissemination System (GDDS),2010,"Demographic and Health Survey (DHS), 2006","Expenditure survey/budget survey (ES/BS), 1994",Yes,2007,2010,2012,2005
13,AZE,Azerbaijan,Republic of Azerbaijan,AZ,New Azeri manat,Europe & Central Asia,Upper middle income,AZ,2000,2002,...,Consolidated central government,General Data Dissemination System (GDDS),2009,"Demographic and Health Survey (DHS), 2006","Expenditure survey/budget survey (ES/BS), 2012",Yes,2015,2010,2012,2005

In [8]:
df_recet["Income_Group"].value_counts() #Counts 'Income_Group' in df_recet.

Income_Group
Upper middle income    63
Name: count, dtype: int64

In [9]:
df_recet =df_recet.reset_index(drop=True) #Resets 'df_recet' index.
df_recet.head() #Displays the first 5 rows of df_recet.

,Country_Code,Short_Name,Long_Name,2-alpha_code,Currency_Unit,Region,Income_Group,WB-2_code,National_accounts_base_year,National_accounts_reference_year,...,Government_Accounting_concept,IMF_data_dissemination_standard,Latest_population_census,Latest_household_survey,Source_of_most_recent_Income_and_expenditure_data,Vital_registration_complete,Latest_agricultural_census,Latest_industrial_ data,Latest_trade_data,Latest_water_withdrawal_data
0,AGO,Angola,People's Republic of Angola,AO,Angolan kwanza,Sub-Saharan Africa,Upper middle income,AO,2002,1996,...,Budgetary central government,General Data Dissemination System (GDDS),1970,"Malaria Indicator Survey (MIS), 2011","Integrated household survey (IHS), 2008",Yes,2015,2010,2012,2005
1,ALB,Albania,Republic of Albania,AL,Albanian lek,Europe & Central Asia,Upper middle income,AL,Original chained constant price data are resca...,1996,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010,2012,2006
2,ARG,Argentina,Argentine Republic,AR,Argentine peso,Latin America & Caribbean,Upper middle income,AR,2004,1996,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2010,"Multiple Indicator Cluster Survey (MICS), 2011/12","Integrated household survey (IHS), 2012",Yes,2013,2002,2012,2000
3,ASM,American Samoa,American Samoa,AS,U.S. dollar,East Asia & Pacific,Upper middle income,AS,2006,2012,...,Budgetary central government,General Data Dissemination System (GDDS),2010,"Demographic and Health Survey (DHS), 2006","Expenditure survey/budget survey (ES/BS), 1994",Yes,2007,2010,2012,2005
4,AZE,Azerbaijan,Republic of Azerbaijan,AZ,New Azeri manat,Europe & Central Asia,Upper middle income,AZ,2000,2002,...,Consolidated central government,General Data Dissemination System (GDDS),2009,"Demographic and Health Survey (DHS), 2006","Expenditure survey/budget survey (ES/BS), 2012",Yes,2015,2010,2012,2005

In [10]:
df_recet.Country_Code #Accesses the Country_Code column from df_recet.

0     AGO
1     ALB
2     ARG
3     ASM
4     AZE
     ...
58    TUR
59    TUV
60    VCT
61    VEN
62    ZAF
Name: Country_Code, Length: 63, dtype: object

In [11]:
df_recet["Region"].value_counts() #Counts the unique values in the Region column of 'df_recet'.

Region
Latin America & Caribbean     23
Europe & Central Asia         15
East Asia & Pacific            9
Sub-Saharan Africa             8
Middle East & North Africa     7
South Asia                     1
Name: count, dtype: int64

In [12]:
df_recet.Region #Accesses the 'Region' column in 'df_recet'.

0            Sub-Saharan Africa
1         Europe & Central Asia
2     Latin America & Caribbean
3           East Asia & Pacific
4         Europe & Central Asia
                ...
58        Europe & Central Asia
59          East Asia & Pacific
60    Latin America & Caribbean
61    Latin America & Caribbean
62           Sub-Saharan Africa
Name: Region, Length: 63, dtype: object

In [13]:
df_recet.Region.unique() #Returns the unique values in the Region column of 'df_recet'.

array(['Sub-Saharan Africa', 'Europe & Central Asia',
       'Latin America & Caribbean', 'East Asia & Pacific',
       'Middle East & North Africa', 'South Asia'], dtype=object)

In [14]:
df_recet.info() #That will print information on all the columns.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 29 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Country_Code                                       63 non-null     object
 1   Short_Name                                         63 non-null     object
 2   Long_Name                                          63 non-null     object
 3   2-alpha_code                                       62 non-null     object
 4   Currency_Unit                                      63 non-null     object
 5   Region                                             63 non-null     object
 6   Income_Group                                       63 non-null     object
 7   WB-2_code                                          62 non-null     object
 8   National_accounts_base_year                        63 non-null     object
 9   National_accounts_reference_year                   63 non-null     int64
 10  SNA_price_valuation                                63 non-null     object
 11  Lending_category                                   63 non-null     object
 12  Other_groups                                       63 non-null     object
 13  System_of_National_Accounts                        63 non-null     object
 14  Alternative_conversion_factor                      63 non-null     object
 15  PPP_survey_year                                    63 non-null     object
 16  Balance_of_Payments_Manual_in_use                  63 non-null     object
 17  External_debt_Reporting_status                     63 non-null     object
 18  System_of_trade                                    63 non-null     object
 19  Government_Accounting_concept                      63 non-null     object
 20  IMF_data_dissemination_standard                    63 non-null     object
 21  Latest_population_census                           63 non-null     object
 22  Latest_household_survey                            63 non-null     object
 23  Source_of_most_recent_Income_and_expenditure_data  63 non-null     object
 24  Vital_registration_complete                        63 non-null     object
 25  Latest_agricultural_census                         63 non-null     object
 26  Latest_industrial_ data                            63 non-null     int64
 27  Latest_trade_data                                  63 non-null     int64
 28  Latest_water_withdrawal_data                       63 non-null     object
dtypes: int64(3), object(26)
memory usage: 14.4+ KB

# Statistical Modeling

In [15]:
df_recet.describe() #Summarize data such as mean, median, or standard deviation for numeric columns

,National_accounts_reference_year,Latest_industrial_ data,Latest_trade_data
count,63.000000,63.000000,63.000000
mean,1907.238095,2008.349206,2011.317460
std,429.910445,2.410720,1.907755
min,0.000000,2001.000000,2000.000000
25%,2000.000000,2008.000000,2012.000000
50%,2002.000000,2009.000000,2012.000000
75%,2005.000000,2010.000000,2012.000000
max,2012.000000,2010.000000,2012.000000

In [16]:
# Save the filtered DataFrame as a CSV file
df_recet.to_csv('recet.EdStatsCountry_data.csv', index=False)