In [1]:
#import python libraries
import pandas as pd
import numpy as np
import random
import string

In [2]:
df = pd.read_csv("EdStatsCountry.csv") #Using this code we can upload the data
df.head(5) #Displays the first 5 rows of df.

,Country_Code,Short_Name,Table_Name,Long_Name,2-alpha_code,Currency_Unit,Special_Notes,Region,Income_Group,WB-2_code,...,Government_Accounting_concept,IMF_data_dissemination_standard,Latest_population_census,Latest_household_survey,Source_of_most_recent_Income_and_expenditure_data,Vital_registration_complete,Latest_agricultural_census,Latest_industrial_ data,Latest_trade_data,Latest_water_withdrawal_data
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,SNA data for 2000-2011 are updated from offici...,Latin America & Caribbean,High income: nonOECD,AW,...,NaN,NaN,2010,NaN,NaN,Yes,NaN,NaN,2012.0,NaN
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,Consolidated central government,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",NaN,2013/14,NaN,2012.0,2000
2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,"April 2013 database update: Based on IMF data,...",Sub-Saharan Africa,Upper middle income,AO,...,Budgetary central government,General Data Dissemination System (GDDS),1970,"Malaria Indicator Survey (MIS), 2011","Integrated household survey (IHS), 2008",NaN,2015,NaN,NaN,2005
3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010.0,2012.0,2006
4,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,NaN,Europe & Central Asia,High income: nonOECD,AD,...,NaN,NaN,2011. Population figures compiled from adminis...,NaN,NaN,Yes,NaN,NaN,2006.0,NaN

In [3]:
df.shape #Show the how many column & row idividual in the particular table

(241, 31)

In [4]:
df.columns #Returns the list of column names in the

Index(['Country_Code', 'Short_Name', 'Table_Name', 'Long_Name', '2-alpha_code',
       'Currency_Unit', 'Special_Notes', 'Region', 'Income_Group', 'WB-2_code',
       'National_accounts_base_year', 'National_accounts_reference_year',
       'SNA_price_valuation', 'Lending_category', 'Other_groups',
       'System_of_National_Accounts', 'Alternative_conversion_factor',
       'PPP_survey_year', 'Balance_of_Payments_Manual_in_use',
       'External_debt_Reporting_status', 'System_of_trade',
       'Government_Accounting_concept', 'IMF_data_dissemination_standard',
       'Latest_population_census', 'Latest_household_survey',
       'Source_of_most_recent_Income_and_expenditure_data',
       'Vital_registration_complete', 'Latest_agricultural_census',
       'Latest_industrial_ data', 'Latest_trade_data',
       'Latest_water_withdrawal_data'],
      dtype='object')

In [5]:
df.info() #That will print information on all the columns.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 31 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Country_Code                                       241 non-null    object
 1   Short_Name                                         241 non-null    object
 2   Table_Name                                         241 non-null    object
 3   Long_Name                                          241 non-null    object
 4   2-alpha_code                                       238 non-null    object
 5   Currency_Unit                                      215 non-null    object
 6   Special_Notes                                      145 non-null    object
 7   Region                                             214 non-null    object
 8   Income_Group                                       214 non-null    object
 9   WB-2_code                                          240 non-null    object
 10  National_accounts_base_year                        205 non-null    object
 11  National_accounts_reference_year                   32 non-null     float64
 12  SNA_price_valuation                                197 non-null    object
 13  Lending_category                                   144 non-null    object
 14  Other_groups                                       58 non-null     object
 15  System_of_National_Accounts                        215 non-null    object
 16  Alternative_conversion_factor                      47 non-null     object
 17  PPP_survey_year                                    145 non-null    object
 18  Balance_of_Payments_Manual_in_use                  181 non-null    object
 19  External_debt_Reporting_status                     124 non-null    object
 20  System_of_trade                                    200 non-null    object
 21  Government_Accounting_concept                      161 non-null    object
 22  IMF_data_dissemination_standard                    181 non-null    object
 23  Latest_population_census                           213 non-null    object
 24  Latest_household_survey                            141 non-null    object
 25  Source_of_most_recent_Income_and_expenditure_data  160 non-null    object
 26  Vital_registration_complete                        111 non-null    object
 27  Latest_agricultural_census                         142 non-null    object
 28  Latest_industrial_ data                            107 non-null    float64
 29  Latest_trade_data                                  185 non-null    float64
 30  Latest_water_withdrawal_data                       179 non-null    object
dtypes: float64(3), object(28)
memory usage: 58.5+ KB

In [6]:
df['Income_Group'].unique() #Show all type of movie name

array(['High income: nonOECD', 'Low income', 'Upper middle income', nan,
       'Lower middle income', 'High income: OECD'], dtype=object)

# Data Filtering

In [7]:
# Filter the DataFrame and save it to 'df_remove'
df_remove = df[df['Income_Group'] == 'Upper middle income']

# Preview the first few rows of 'df_remove'
df_remove.head()

,Country_Code,Short_Name,Table_Name,Long_Name,2-alpha_code,Currency_Unit,Special_Notes,Region,Income_Group,WB-2_code,...,Government_Accounting_concept,IMF_data_dissemination_standard,Latest_population_census,Latest_household_survey,Source_of_most_recent_Income_and_expenditure_data,Vital_registration_complete,Latest_agricultural_census,Latest_industrial_ data,Latest_trade_data,Latest_water_withdrawal_data
2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,"April 2013 database update: Based on IMF data,...",Sub-Saharan Africa,Upper middle income,AO,...,Budgetary central government,General Data Dissemination System (GDDS),1970,"Malaria Indicator Survey (MIS), 2011","Integrated household survey (IHS), 2008",NaN,2015,NaN,NaN,2005
3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010.0,2012.0,2006
7,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,NaN,Latin America & Caribbean,Upper middle income,AR,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2010,"Multiple Indicator Cluster Survey (MICS), 2011/12","Integrated household survey (IHS), 2012",Yes,2013,2002.0,2012.0,2000
9,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,NaN,East Asia & Pacific,Upper middle income,AS,...,NaN,NaN,2010,NaN,NaN,Yes,2007,NaN,NaN,NaN
13,AZE,Azerbaijan,Azerbaijan,Republic of Azerbaijan,AZ,New Azeri manat,April 2012 database update: National accounts ...,Europe & Central Asia,Upper middle income,AZ,...,Consolidated central government,General Data Dissemination System (GDDS),2009,"Demographic and Health Survey (DHS), 2006","Expenditure survey/budget survey (ES/BS), 2012",Yes,2015,2010.0,2012.0,2005

In [8]:
df_remove["Income_Group"].value_counts() #Counts 'Income_Group' in df_remove.

Income_Group
Upper middle income    55
Name: count, dtype: int64

In [9]:
df_remove =df_remove.reset_index(drop=True) #Resets 'df_remove' index.
df_remove.head() #Displays the first 5 rows of df_recet.

,Country_Code,Short_Name,Table_Name,Long_Name,2-alpha_code,Currency_Unit,Special_Notes,Region,Income_Group,WB-2_code,...,Government_Accounting_concept,IMF_data_dissemination_standard,Latest_population_census,Latest_household_survey,Source_of_most_recent_Income_and_expenditure_data,Vital_registration_complete,Latest_agricultural_census,Latest_industrial_ data,Latest_trade_data,Latest_water_withdrawal_data
0,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,"April 2013 database update: Based on IMF data,...",Sub-Saharan Africa,Upper middle income,AO,...,Budgetary central government,General Data Dissemination System (GDDS),1970,"Malaria Indicator Survey (MIS), 2011","Integrated household survey (IHS), 2008",NaN,2015,NaN,NaN,2005
1,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010.0,2012.0,2006
2,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,NaN,Latin America & Caribbean,Upper middle income,AR,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2010,"Multiple Indicator Cluster Survey (MICS), 2011/12","Integrated household survey (IHS), 2012",Yes,2013,2002.0,2012.0,2000
3,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,NaN,East Asia & Pacific,Upper middle income,AS,...,NaN,NaN,2010,NaN,NaN,Yes,2007,NaN,NaN,NaN
4,AZE,Azerbaijan,Azerbaijan,Republic of Azerbaijan,AZ,New Azeri manat,April 2012 database update: National accounts ...,Europe & Central Asia,Upper middle income,AZ,...,Consolidated central government,General Data Dissemination System (GDDS),2009,"Demographic and Health Survey (DHS), 2006","Expenditure survey/budget survey (ES/BS), 2012",Yes,2015,2010.0,2012.0,2005

In [10]:
column_to_check = '2-alpha_code'# Replace 'ema' with the correct column name if it's different

# Generate random 2-letter code only where 'column_to_check' is null
df_remove['2-alpha_code'] = df_remove['2-alpha_code'].where(
    df_remove[column_to_check].notnull(), 
    [''.join(random.choices(string.ascii_uppercase, k=2)) for _ in range(df_remove[column_to_check].isnull().sum())]
)
# Display the updated DataFrame
df_remove.head()

,Country_Code,Short_Name,Table_Name,Long_Name,2-alpha_code,Currency_Unit,Special_Notes,Region,Income_Group,WB-2_code,...,Government_Accounting_concept,IMF_data_dissemination_standard,Latest_population_census,Latest_household_survey,Source_of_most_recent_Income_and_expenditure_data,Vital_registration_complete,Latest_agricultural_census,Latest_industrial_ data,Latest_trade_data,Latest_water_withdrawal_data
0,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,"April 2013 database update: Based on IMF data,...",Sub-Saharan Africa,Upper middle income,AO,...,Budgetary central government,General Data Dissemination System (GDDS),1970,"Malaria Indicator Survey (MIS), 2011","Integrated household survey (IHS), 2008",NaN,2015,NaN,NaN,2005
1,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010.0,2012.0,2006
2,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,NaN,Latin America & Caribbean,Upper middle income,AR,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2010,"Multiple Indicator Cluster Survey (MICS), 2011/12","Integrated household survey (IHS), 2012",Yes,2013,2002.0,2012.0,2000
3,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,NaN,East Asia & Pacific,Upper middle income,AS,...,NaN,NaN,2010,NaN,NaN,Yes,2007,NaN,NaN,NaN
4,AZE,Azerbaijan,Azerbaijan,Republic of Azerbaijan,AZ,New Azeri manat,April 2012 database update: National accounts ...,Europe & Central Asia,Upper middle income,AZ,...,Consolidated central government,General Data Dissemination System (GDDS),2009,"Demographic and Health Survey (DHS), 2006","Expenditure survey/budget survey (ES/BS), 2012",Yes,2015,2010.0,2012.0,2005

In [11]:
column_to_check = 'WB-2_code'# Replace 'ema' with the correct column name if it's different

# Generate random 2-letter code only where 'column_to_check' is null
df_remove['WB-2_code'] = df_remove['WB-2_code'].where(
    df_remove[column_to_check].notnull(), 
    [''.join(random.choices(string.ascii_uppercase, k=2)) for _ in range(df_remove[column_to_check].isnull().sum())]
)
# Display the updated DataFrame
df_remove.head()

,Country_Code,Short_Name,Table_Name,Long_Name,2-alpha_code,Currency_Unit,Special_Notes,Region,Income_Group,WB-2_code,...,Government_Accounting_concept,IMF_data_dissemination_standard,Latest_population_census,Latest_household_survey,Source_of_most_recent_Income_and_expenditure_data,Vital_registration_complete,Latest_agricultural_census,Latest_industrial_ data,Latest_trade_data,Latest_water_withdrawal_data
0,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,"April 2013 database update: Based on IMF data,...",Sub-Saharan Africa,Upper middle income,AO,...,Budgetary central government,General Data Dissemination System (GDDS),1970,"Malaria Indicator Survey (MIS), 2011","Integrated household survey (IHS), 2008",NaN,2015,NaN,NaN,2005
1,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010.0,2012.0,2006
2,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,NaN,Latin America & Caribbean,Upper middle income,AR,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2010,"Multiple Indicator Cluster Survey (MICS), 2011/12","Integrated household survey (IHS), 2012",Yes,2013,2002.0,2012.0,2000
3,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,NaN,East Asia & Pacific,Upper middle income,AS,...,NaN,NaN,2010,NaN,NaN,Yes,2007,NaN,NaN,NaN
4,AZE,Azerbaijan,Azerbaijan,Republic of Azerbaijan,AZ,New Azeri manat,April 2012 database update: National accounts ...,Europe & Central Asia,Upper middle income,AZ,...,Consolidated central government,General Data Dissemination System (GDDS),2009,"Demographic and Health Survey (DHS), 2006","Expenditure survey/budget survey (ES/BS), 2012",Yes,2015,2010.0,2012.0,2005

In [12]:
df_remove.Country_Code #Accesses the Country_Code column from df_remove.

0     AGO
1     ALB
2     ARG
3     ASM
4     AZE
5     BGR
6     BIH
7     BLR
8     BLZ
9     BRA
10    BWA
11    CHN
12    COL
13    CRI
14    CUB
15    DMA
16    DOM
17    DZA
18    ECU
19    FJI
20    GAB
21    GRD
22    HUN
23    IRN
24    IRQ
25    JAM
26    JOR
27    KAZ
28    LBN
29    LBY
30    LCA
31    MDV
32    MEX
33    MHL
34    MKD
35    MNE
36    MUS
37    MYS
38    NAM
39    PAN
40    PER
41    PLW
42    ROU
43    SRB
44    SUR
45    SYC
46    THA
47    TKM
48    TON
49    TUN
50    TUR
51    TUV
52    VCT
53    VEN
54    ZAF
Name: Country_Code, dtype: object

In [13]:
df_remove["Region"].value_counts() #Counts the unique values in the Region column of 'df_remove'.

Region
Latin America & Caribbean     18
Europe & Central Asia         13
East Asia & Pacific            9
Sub-Saharan Africa             7
Middle East & North Africa     7
South Asia                     1
Name: count, dtype: int64

In [14]:
df_remove.Region #Accesses the 'Region' column in 'df_remove'.

0             Sub-Saharan Africa
1          Europe & Central Asia
2      Latin America & Caribbean
3            East Asia & Pacific
4          Europe & Central Asia
5          Europe & Central Asia
6          Europe & Central Asia
7          Europe & Central Asia
8      Latin America & Caribbean
9      Latin America & Caribbean
10            Sub-Saharan Africa
11           East Asia & Pacific
12     Latin America & Caribbean
13     Latin America & Caribbean
14     Latin America & Caribbean
15     Latin America & Caribbean
16     Latin America & Caribbean
17    Middle East & North Africa
18     Latin America & Caribbean
19           East Asia & Pacific
20            Sub-Saharan Africa
21     Latin America & Caribbean
22         Europe & Central Asia
23    Middle East & North Africa
24    Middle East & North Africa
25     Latin America & Caribbean
26    Middle East & North Africa
27         Europe & Central Asia
28    Middle East & North Africa
29    Middle East & North Africa
30     Latin America & Caribbean
31                    South Asia
32     Latin America & Caribbean
33           East Asia & Pacific
34         Europe & Central Asia
35         Europe & Central Asia
36            Sub-Saharan Africa
37           East Asia & Pacific
38            Sub-Saharan Africa
39     Latin America & Caribbean
40     Latin America & Caribbean
41           East Asia & Pacific
42         Europe & Central Asia
43         Europe & Central Asia
44     Latin America & Caribbean
45            Sub-Saharan Africa
46           East Asia & Pacific
47         Europe & Central Asia
48           East Asia & Pacific
49    Middle East & North Africa
50         Europe & Central Asia
51           East Asia & Pacific
52     Latin America & Caribbean
53     Latin America & Caribbean
54            Sub-Saharan Africa
Name: Region, dtype: object

In [15]:
df_remove.Region.unique() #Returns the unique values in the Region column of 'df_remove'.

array(['Sub-Saharan Africa', 'Europe & Central Asia',
       'Latin America & Caribbean', 'East Asia & Pacific',
       'Middle East & North Africa', 'South Asia'], dtype=object)

# Statistical Modeling

In [16]:
df_remove.describe() #Summarize data such as mean, median, or standard deviation for numeric columns

,National_accounts_reference_year,Latest_industrial_ data,Latest_trade_data
count,7.000000,28.000000,50.000000
mean,2000.142857,2008.642857,2011.140000
std,3.287784,2.376027,2.109357
min,1996.000000,2001.000000,2000.000000
25%,1998.000000,2008.750000,2011.250000
50%,2000.000000,2010.000000,2012.000000
75%,2002.000000,2010.000000,2012.000000
max,2005.000000,2010.000000,2012.000000

In [17]:
df_filtering = df_remove[df_remove.Region=="Europe & Central Asia"] #Show only the "Europe & Central Asia" columns. 
df_filtering.head() #Displays the first 5 rows of df_recet.

,Country_Code,Short_Name,Table_Name,Long_Name,2-alpha_code,Currency_Unit,Special_Notes,Region,Income_Group,WB-2_code,...,Government_Accounting_concept,IMF_data_dissemination_standard,Latest_population_census,Latest_household_survey,Source_of_most_recent_Income_and_expenditure_data,Vital_registration_complete,Latest_agricultural_census,Latest_industrial_ data,Latest_trade_data,Latest_water_withdrawal_data
1,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010.0,2012.0,2006
4,AZE,Azerbaijan,Azerbaijan,Republic of Azerbaijan,AZ,New Azeri manat,April 2012 database update: National accounts ...,Europe & Central Asia,Upper middle income,AZ,...,Consolidated central government,General Data Dissemination System (GDDS),2009,"Demographic and Health Survey (DHS), 2006","Expenditure survey/budget survey (ES/BS), 2012",Yes,2015,2010.0,2012.0,2005
5,BGR,Bulgaria,Bulgaria,Republic of Bulgaria,BG,Bulgarian lev,April 2011 database update: The National Stati...,Europe & Central Asia,Upper middle income,BG,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,Living Standards Measurement Study Survey (LSM...,"Expenditure survey/budget survey (ES/BS), 2007",Yes,2010,2010.0,2012.0,2009
6,BIH,Bosnia and Herzegovina,Bosnia and Herzegovina,Bosnia and Herzegovina,BA,Bosnia and Herzegovina convertible mark,NaN,Europe & Central Asia,Upper middle income,BA,...,Consolidated central government,General Data Dissemination System (GDDS),2013,"Multiple Indicator Cluster Survey (MICS), 2011/12",Living Standards Measurement Study Survey (LSM...,Yes,NaN,NaN,2012.0,2009
7,BLR,Belarus,Belarus,Republic of Belarus,BY,Belarusian rubel,NaN,Europe & Central Asia,Upper middle income,BY,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2009,"Multiple Indicator Cluster Survey (MICS), 2012","Expenditure survey/budget survey (ES/BS), 2012",Yes,NaN,2009.0,2012.0,2000

In [18]:
df_filtering.Region.unique() #Returns the unique values in the Region column of 'df_remove'.

array(['Europe & Central Asia'], dtype=object)

In [19]:
df_filtering =df_filtering.reset_index(drop=True) #Resets 'df_remove' index.
df_filtering.head(20) #Displays the first 20 rows of df_remove.

,Country_Code,Short_Name,Table_Name,Long_Name,2-alpha_code,Currency_Unit,Special_Notes,Region,Income_Group,WB-2_code,...,Government_Accounting_concept,IMF_data_dissemination_standard,Latest_population_census,Latest_household_survey,Source_of_most_recent_Income_and_expenditure_data,Vital_registration_complete,Latest_agricultural_census,Latest_industrial_ data,Latest_trade_data,Latest_water_withdrawal_data
0,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010.0,2012.0,2006
1,AZE,Azerbaijan,Azerbaijan,Republic of Azerbaijan,AZ,New Azeri manat,April 2012 database update: National accounts ...,Europe & Central Asia,Upper middle income,AZ,...,Consolidated central government,General Data Dissemination System (GDDS),2009,"Demographic and Health Survey (DHS), 2006","Expenditure survey/budget survey (ES/BS), 2012",Yes,2015,2010.0,2012.0,2005
2,BGR,Bulgaria,Bulgaria,Republic of Bulgaria,BG,Bulgarian lev,April 2011 database update: The National Stati...,Europe & Central Asia,Upper middle income,BG,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,Living Standards Measurement Study Survey (LSM...,"Expenditure survey/budget survey (ES/BS), 2007",Yes,2010,2010.0,2012.0,2009
3,BIH,Bosnia and Herzegovina,Bosnia and Herzegovina,Bosnia and Herzegovina,BA,Bosnia and Herzegovina convertible mark,NaN,Europe & Central Asia,Upper middle income,BA,...,Consolidated central government,General Data Dissemination System (GDDS),2013,"Multiple Indicator Cluster Survey (MICS), 2011/12",Living Standards Measurement Study Survey (LSM...,Yes,NaN,NaN,2012.0,2009
4,BLR,Belarus,Belarus,Republic of Belarus,BY,Belarusian rubel,NaN,Europe & Central Asia,Upper middle income,BY,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2009,"Multiple Indicator Cluster Survey (MICS), 2012","Expenditure survey/budget survey (ES/BS), 2012",Yes,NaN,2009.0,2012.0,2000
5,HUN,Hungary,Hungary,Hungary,HU,Hungarian forint,April 2012 database update: Based on data from...,Europe & Central Asia,Upper middle income,HU,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"World Health Survey (WHS), 2003","Expenditure survey/budget survey (ES/BS), 2007",Yes,2010,2009.0,2012.0,2007
6,KAZ,Kazakhstan,Kazakhstan,Republic of Kazakhstan,KZ,Kazakh tenge,NaN,Europe & Central Asia,Upper middle income,KZ,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2009,"Multiple Indicator Cluster Survey (MICS), 2010/11","Expenditure survey/budget survey (ES/BS), 2012",Yes,NaN,NaN,2012.0,2010
7,MKD,Macedonia,"Macedonia, FYR",Former Yugoslav Republic of Macedonia,MK,Macedonian denar,April 2012 database update: Based on official ...,Europe & Central Asia,Upper middle income,MK,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2002,"Multiple Indicator Cluster Survey (MICS), 2011","Expenditure survey/budget survey (ES/BS), 2009",Yes,2007,2010.0,2012.0,2007
8,MNE,Montenegro,Montenegro,Montenegro,ME,Euro,Montenegro declared independence from Serbia a...,Europe & Central Asia,Upper middle income,ME,...,NaN,General Data Dissemination System (GDDS),2011,"Multiple Indicator Cluster Survey (MICS), 2005/06","Expenditure survey/budget survey (ES/BS), 2011",Yes,2010,NaN,2012.0,2010
9,ROU,Romania,Romania,Romania,RO,New Romanian leu,National accounts have been revised based on d...,Europe & Central Asia,Upper middle income,RO,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"Reproductive Health Survey (RHS), 1999","Labor force survey (LFS), 2010",Yes,2010,2010.0,2012.0,2009
10,SRB,Serbia,Serbia,Republic of Serbia,RS,New Serbian dinar,Montenegro declared independence from Serbia a...,Europe & Central Asia,Upper middle income,YF,...,Consolidated central government,General Data Dissemination System (GDDS),2011,"Multiple Indicator Cluster Survey (MICS), 2010","Integrated household survey (IHS), 2010",Yes,2012,2010.0,NaN,2009
11,TKM,Turkmenistan,Turkmenistan,Turkmenistan,TM,New Turkmen manat,"On January 1, 2009, the Turkmen manat was rede...",Europe & Central Asia,Upper middle income,TM,...,NaN,NaN,2012,"Multiple Indicator Cluster Survey (MICS), 2011",Living Standards Measurement Study Survey (LSM...,Yes,NaN,NaN,2000.0,2004
12,TUR,Turkey,Turkey,Republic of Turkey,TR,New Turkish lira,NaN,Europe & Central Asia,Upper middle income,TR,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey (DHS), 2003; Wor...","Labor force survey (LFS), 2009",NaN,NaN,2009.0,2012.0,2003

In [20]:
df_filtering.Region #Accesses the 'Region' column in 'df_remove'.

0     Europe & Central Asia
1     Europe & Central Asia
2     Europe & Central Asia
3     Europe & Central Asia
4     Europe & Central Asia
5     Europe & Central Asia
6     Europe & Central Asia
7     Europe & Central Asia
8     Europe & Central Asia
9     Europe & Central Asia
10    Europe & Central Asia
11    Europe & Central Asia
12    Europe & Central Asia
Name: Region, dtype: object

In [21]:
df_filtering.Country_Code #Accesses the Country_Code column from df_remove.

0     ALB
1     AZE
2     BGR
3     BIH
4     BLR
5     HUN
6     KAZ
7     MKD
8     MNE
9     ROU
10    SRB
11    TKM
12    TUR
Name: Country_Code, dtype: object

In [22]:
df_filtering.info() #That will print information on all the columns.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 31 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Country_Code                                       13 non-null     object
 1   Short_Name                                         13 non-null     object
 2   Table_Name                                         13 non-null     object
 3   Long_Name                                          13 non-null     object
 4   2-alpha_code                                       13 non-null     object
 5   Currency_Unit                                      13 non-null     object
 6   Special_Notes                                      8 non-null      object
 7   Region                                             13 non-null     object
 8   Income_Group                                       13 non-null     object
 9   WB-2_code                                          13 non-null     object
 10  National_accounts_base_year                        13 non-null     object
 11  National_accounts_reference_year                   7 non-null      float64
 12  SNA_price_valuation                                13 non-null     object
 13  Lending_category                                   12 non-null     object
 14  Other_groups                                       0 non-null      object
 15  System_of_National_Accounts                        13 non-null     object
 16  Alternative_conversion_factor                      6 non-null      object
 17  PPP_survey_year                                    12 non-null     object
 18  Balance_of_Payments_Manual_in_use                  13 non-null     object
 19  External_debt_Reporting_status                     13 non-null     object
 20  System_of_trade                                    13 non-null     object
 21  Government_Accounting_concept                      11 non-null     object
 22  IMF_data_dissemination_standard                    12 non-null     object
 23  Latest_population_census                           13 non-null     object
 24  Latest_household_survey                            13 non-null     object
 25  Source_of_most_recent_Income_and_expenditure_data  13 non-null     object
 26  Vital_registration_complete                        12 non-null     object
 27  Latest_agricultural_census                         8 non-null      object
 28  Latest_industrial_ data                            9 non-null      float64
 29  Latest_trade_data                                  12 non-null     float64
 30  Latest_water_withdrawal_data                       13 non-null     object
dtypes: float64(3), object(28)
memory usage: 3.3+ KB

In [23]:
# Save the filtered DataFrame as a CSV file
df_filtering.to_csv('filtering.EdStatsCountry_data.csv', index=False)  # Set index=False to avoid saving the index as a separate column

# Statistical Modeling

In [24]:
df_filtering.describe() #Summarize data such as mean, median, or standard deviation for numeric columns

,National_accounts_reference_year,Latest_industrial_ data,Latest_trade_data
count,7.000000,9.000000,12.000000
mean,2000.142857,2009.666667,2011.000000
std,3.287784,0.500000,3.464102
min,1996.000000,2009.000000,2000.000000
25%,1998.000000,2009.000000,2012.000000
50%,2000.000000,2010.000000,2012.000000
75%,2002.000000,2010.000000,2012.000000
max,2005.000000,2010.000000,2012.000000